### ISSUE TITLE
Is this being actively maintained?

### ISSUE THREAD

**Issue by neil-s** [notablemind/jupyter-nodejs#20]
I'm using ijavascript at the moment, but finding it quite rough around the edges. The output it prints is very unpredictable for example - sometimes it doesn't show the output from console.log commands, and it always prints the last object created, cluttering up the output. It also doesn't seem to maintain session very well across cells, sometimes necessitating a re-run of all the cells for code to work correctly. This repo looks like it has nicer output, but I wanted to check whether it's active before switching, since it isn't listed on the Jupyter site.

**Comment by jaredly** [comment]
I'm not actively using it at the moment, but it's something I'm really interested in, and I'm happy to fix bugs that people find

**Comment by n-riesco** [comment]
@neil-s  I think you're describing [this issue in IJavascript](https://github.com/n-riesco/ijavascript/issues/58). I believe it's been fixed recently. Please, could you check whether the bug is still present in the latest version (5.0.11-beta.0)?

Regarding the output, there are several ways to disable the output of a cell. Please, could you open an issue on the IJavascript repository, so that I can advise you of the options available?

Disclaimer: I'm IJavascript's author.

**Comment by neil-s** [comment]
Oh wow, @n-riesco , thanks for maintaining IJavascript actively enough to monitor issues out here! :+1: I think I got the version that came pre-installed with Anaconda, or it was on my AWS machine already somehow. Will try and update. The more I think about it, the more I realize about the complexities of creating a notebook for asynchronous code, so nicely done on fixing the issue.
